name: Continuous Deployment with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.x' # Replace with the Go version you want to use

    - name: Build the Go application
      run: go build

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: your-docker-repo/your-image-name:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
